source/src/main/kotlin/com/theguardian/source/typography/Typography.kt
source/src/main/kotlin/com/theguardian/source/typography/TypographyPreview.kt
source/src/main/kotlin/com/theguardian/source/utils/fontFamilyResource.kt

Hand crafted app typography presets tokens to match [those in source](https://theguardian.design/2a1e5182b/p/01555f-typography-presets/b/814fba).
Note: Some fonts mentioned in the presets aren't available in the app. Nearest approximation with the correct weight/style have been used. The missing fonts are:
1. Egyptian Bold
2. Egyptian Bold Italic
3. Text Sans Italic
Haven't done test integration on CI. At the moment, the best way to test is to verify individual token in `Typography.kt` with the description at the link above.
This isn't practical, so _just accept this_ for now.

Add Typgraphy presets

---

.github/workflows/lint.yml

Ensures the lint checks only run when files within the `android` folder or the `.github` folder are changed.

[Android] Add path constraint for running lint checks

---

README.md
Sources/Source/ColorPalette/ColorPalette.swift
Sources/Source/ColorPalette/Extensions/UIColor+Dynamic.swift
Sources/Source/ColorPalette/Palette.xcassets/Brand300.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Brand400.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Brand500.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Brand600.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Brand800.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/BrandAlt200.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/BrandAlt400.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Culture700.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Culture800.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Neutral0.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Neutral10.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Neutral100.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Neutral20.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Neutral36.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Neutral38.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Neutral46.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Neutral60.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Neutral7.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Neutral86.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Neutral93.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Neutral97.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Sport400.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Sport500.colorset/Contents.json

This PR adds a new `ColorPalette` class to the Source iOS swift package, for colour reference. It simply moves the code that previously existed inside the `ColorPalette` local swift package that lived in the main app previously. 
To test this you can check out this branch which update the live app to reference Guardian colours via Source - https://github.com/guardian/ios-live/tree/CQ/replace-colour-palette-with-Source-library. 
Once this has been merged, I will open a PR on the live app repo to replace the existing ColorPalette framework with the Source framework. 
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/peop …

Feature - add colour palette to swift package

---

.github/workflows/lint.yml

Using the path filter means the checks stay pending for iOS PRs. This replaces path filter with a job to check for `changes`. The lint jobs are dependent on the `changes` job, and are skipped if no changes found.
This makes the checks run on Android changes and passes quickly for iOS (or README) only changes.
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey …

Run lint checks for android changes but pass for non-android changes

---

.github/workflows/release.yml
android/README.md
android/build.gradle.kts
android/gradle/libs.versions.toml
android/source/build.gradle.kts

Switches to [Gradle nexus publish plugin](https://github.com/gradle-nexus/publish-plugin/) for publishing the library to Sonatype. This plugin supports immediately releasing the updates to production. The existing `maven-publish` based solution only uploads to staging. It required manual update to production by logging into Sonatype. The nexus plugin removes that manual step.
To test this, I updated the library version to `0.1.1` (from `0.1.0`) and [published it successfully](https://central.sonatype.com/artifact/com.gu.source/source-android).

Add nexus gradle publish plugin to auto close staging and release

---

android/gradle/libs.versions.toml
android/sample/src/main/kotlin/com/gu/source/MainActivity.kt
android/source/src/main/kotlin/com/gu/source/presets/palette/Palette.kt

Changing palette colour preset names to match the naming pattern for Typography presets, and Material colours.

Remove `_` from palette colour names

---

android/gradle/libs.versions.toml
android/sample/src/main/kotlin/com/gu/source/MainActivity.kt
android/sample/src/main/kotlin/com/gu/source/PalettePreview.kt
android/source/src/main/kotlin/com/gu/source/presets/palette/Palette.kt
android/source/src/main/res/values/palette.xml

Updates palette colours based on @akemitakagi 's feedback [document.](https://docs.google.com/document/d/1chQ2EqUdkjvzqn8hHgAthCL84M-XWeQ2hQg0_BsrBsg/edit)
I've left the `opinion_300` in but marked it as deprecated with recommendation to use 400 instead.
Also added a sheet with all palette pills to the sample app (screenshot below).
Build and run the sample app to see all the palette colours, and maybe confirm them with Akemi's sheet.
- Code review from @guardian/android-developers or @guardian/ios-developers
- Optional code/API review from @guardian/client-side-infra

Update palette colours

---

README.md
android/sample/src/main/kotlin/com/gu/source/MainActivity.kt
android/source/src/main/kotlin/com/gu/source/components/buttons/ButtonColours.kt
android/source/src/main/kotlin/com/gu/source/components/buttons/PlainSourceButton.kt
android/source/src/main/kotlin/com/gu/source/components/buttons/SourceButton.kt

Created `PlainSourceButton` and `PlainSourceContentButton` variants. These take a `ButtonColours` object instead of `theme` and `priority`. They are intended to be used for custom colour combinations.
Check out the unthemed button in sample.
- Code review from @guardian/android-developers or @guardian/ios-developers
- Optional code/API review from @guardian/client-side-infra
| Light | | |
| Dark | | |

Add button variant that allows custom colours

---

.github/workflows/release.yml
android/build.gradle.kts
android/gradle/libs.versions.toml

Use token auth for Sonatype - see https://github.com/guardian/gha-scala-library-release-workflow/pull/23

Use token auth for Sonatype

---

Sources/Source/Typography/Typography.swift

As part of the new fairground front designs, the headline font size can be as big as 50px. This PR adds new presets for that size. 
While doing this I also noticed we didn't have typography tokens for `HeadlineLightItalic` and so have added them too. 
https://www.figma.com/design/kSmjgtoTWiG8N7HXxFoGEE/%E2%97%90-Apps-library?node-id=5-65&m=dev
For now there is no way of verifying the output of the typography presets until the sample app is extended for Typography.
| Light | | |
| Dark | | |

[iOS] Update typography presets to include size 50 plus headline italic

---

Sources/Source/Components/Buttons/IconButton.swift

Small PR to update the disabled opacity in dark mode, this manages the design approach we've taken for the secondary colour - in that in dark mode it is 40% rather than 20% so that it's more visible. 
I've also made a small change to the `IconButton` initialiser so that the `disabled` property takes a default value of false since it is in rare occasions this is likely to be used. 
| `Before` | `After` |
| --- | --- |

iOS - Update disabled opacity of icon button 

---

Sources/Source/Components/PaginationProgressBar.swift

This PR animates the change to the selected index triggered by the buttons within the `PaginationProgressBar` - this allows the images in the slideshow to animate into view. 
| `Before` | `After` |
| --- | --- |
https://github.com/user-attachments/assets/c2a2227d-4466-4a2f-9cb3-6168ea27df42 | https://github.com/user-attachments/assets/0771a8c2-7cfc-411f-bfb5-59cb49ac5e05

iOS - Animate change of index triggered by progress button 

---

Sources/Source/Components/Buttons/IconButton.swift

As spotted in this [PR](https://github.com/guardian/ios-live/pull/8038#issuecomment-2258456518) - the icon presets were too small, since the icon svg already have their own padding. 
This PR updates the sizing and padding so that the total size still matches that set in the design system 
This can be tested as part of the PR on iOS live - I have added a screenshot from that branch here to confirm the impact on the size of the chevron. 
| `Before` | `After` |
| --- | --- |

iOS - Update icon sizes and padding 

---

android/config/detekt.yml
android/gradle/libs.versions.toml
android/sample/src/main/kotlin/com/gu/source/ImagePagerWithProgressIndicator.kt
android/sample/src/main/kotlin/com/gu/source/MainActivity.kt
android/source/src/main/kotlin/com/gu/source/components/buttons/PlainSourceButton.kt
android/source/src/main/kotlin/com/gu/source/components/buttons/SourceButton.kt
android/source/src/main/kotlin/com/gu/source/components/buttons/SourceIconButton.kt
android/source/src/main/kotlin/com/gu/source/components/pager/PagerProgressBar.kt
android/source/src/main/kotlin/com/gu/source/utils/PreviewAnnotations.kt

Updates the multi-preview annotations' name and adds a scaled font preview.
The updated annotations now match those in the news app which will be replaced by these.

Update multi preview annotations to add scaled font preview

---

.github/workflows/android-docs.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/test.yml
README.md
android/README.md

* Update the android-docs workflow with correct permissions and git setup
* Publish html docs instead of GFM docs from dokka so they appear with kotlin branding
* Add links to API documentation in readme
* Make links to other README's relative
Asides:
* Update actions/checkout to v4 where it'd been forgotten
* Add repository check to release workflow

Dokka 2: Fix commit issues and link from docs

---

android/gradle/libs.versions.toml
android/source/src/main/kotlin/com/gu/source/utils/PreviewAnnotations.kt

We've got a few reports of UI not rendering correctly on narrow devices. This PR adds a preview for Samsung S20 (360px width viewport) so we can preview the UI on these devices while developing.
See the preview in `MainActivity` for a narrower version.

Add a narrow width device to multi preview annotation

---

Sources/Source/Components/Buttons/IconButton.swift
Sources/Source/Components/PaginationButtons.swift
Sources/Source/Components/PaginationProgressBar.swift
Sources/Source/Components/ScrollingPaginationIndicator.swift

As part of upcoming work on Fairground in which we want to display pagination buttons next to carousel components on tablet, this PR extracts the pagination buttons from the `PaginationProgressBar`, so that they can be used independently. 
It also does some refactoring of the logic to remove unnecessary bindings and keeps some of the `canNavigateForward` `canNavigateBack` logic internal to the buttons. 
You can test this out by using this ios-live branch which points to this version of the `source-apps` repo - you'll need to test on tablet in order for the buttons to be displayed. 
Importantly it would be good to check that image slide shows are working as expected. If there isn't one on PROD fronts, let me know and I can help you test on CODE.

iOS - Separate out pagination button from progress bar component

---

android/gradle/libs.versions.toml
android/source/build.gradle.kts

Changes license url to standard public one so that we can revert https://github.com/guardian/android-feast/pull/480
The non standard license URL was causing the license task to fail.

Use standard license URL

---

Sources/Source/Components/PaginationButtons.swift
Sources/Source/Components/PaginationProgressBar.swift

This PR updates the `PaginationButtons` component so that it accepts a `canNavigateForward` parameter rather than `pageCount` this allows us the foward disabled state to be determined used of the component, which is especially important for carousels since the number of items to be displayed at once varies depending on the layout, eg. small carousel shows 2 items per page, whereas medium carousel shows 4 on tablet. 
The carousel component in the iOS live app can now own this logic and determine based on row and column width, whether or not the next button should be disabled. 
| Light | | |
| Dark | | |

iOS - Refactor pager buttons forward disabled state

---

Sources/Source/Components/PaginationButtons.swift
Sources/Source/Components/PaginationProgressBar.swift
Sources/Source/Components/ScrollingPaginationIndicator.swift

After making `selectedIndex` used by the `PaginationButtons` component an optional Integer, we have found that the image slideshow used in the app is broken due to the `TabView` component being unable to compare the tags which are `Int` and the selected item `Int?`. 
This PR makes a change to revert this value back to a simple `Int`. There is another change in the ios-live repo which depends on this change to fix the slideshow. 
| Light | | |
| Dark | | |

Remove optionality from selected index in PaginationButtons component

---

android/build-logic/convention/src/main/kotlin/com/theguardian/convention/DetektPlugin.kt
android/build.gradle.kts

Reduces Gradle configuration work by configuring tasks lazily.
* Use `configureEach` after `withType`
https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#:~:text=TaskCollection.whenTaskAdded(),DomainObjectCollection.configureEach()%20instead.
Build config changes - confirm the checks pass.

Configure tasks lazily with `configureEach`

---

Sources/Source/Typography/Typography.swift

Correct typo on `textEgyp17` in `Typography.swift`

---

Sources/Source/Components/Buttons/ButtonPriority.swift
Sources/Source/Components/Buttons/ButtonStyle+SourceButtonStyle.swift

To be more in line with default button styles provided by Apple, our buttons should not have an infinite max width by default.
This PR is a dependency for [this PR](https://github.com/guardian/ios-feast/pull/414). We don't have to worry about this affecting the live app as only Feast uses these components.

iOS Source Buttons: don't make them `maxWidth: .infinity`, fix typo

---

SourceSample/SourceSample.xcodeproj/project.pbxproj
Sources/Source/Components/Buttons/ButtonStyle+SourceButtonStyle.swift
Sources/Source/Components/Buttons/ButtonTheme.swift
Sources/Source/Components/PaginationProgressBar.swift
Sources/Source/Components/ScrollingPaginationIndicator.swift

There is a Source Sample app used to preview some of the Design system components, eg. colours. 
This a macos app and was previously not building due to some iOS specific code not compiling when building for macos. 
As a future improvement we should look at adding a check which involves building the SourceSample app. 
| Light | | |
| Dark | | |

Fix Source Sample app

---

.github/workflows/release.yml

This PR removes Github releases as a trigger for publishing to maven central.
We recently created Github releases for all our releases so far. This triggered several publishing flows - sometimes multiple ones for each release. The resulting flood of releases overwhelmed our Sonatype servers and has blocked the whole `com.gu` organisation from publishing any updates.

[Android] Remove Github releases as a publishing trigger

---

SourceSample/SourceSample/Color/PaletteViewModel.swift
Sources/Source/ColorPalette/ColorPalette+macos.swift
Sources/Source/ColorPalette/ColorPalette.swift
Sources/Source/ColorPalette/Palette.xcassets/News700.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Opinion700.colorset/Contents.json
Sources/Source/ColorPalette/Palette.xcassets/Sport700.colorset/Contents.json

Ticket: https://github.com/guardian/design-system-advocates/issues/37
Adds Opinion.700, Sport.700 and News.700 colors to the palette
Confirm the new colours in the source-apps sample app
- Code review from @guardian/android-developers or @guardian/ios-developers
- Optional code/API review from @guardian/client-side-infra

Add Opinion.700, Sport.700 and News.700 Colors

---

Sources/Source/ColorPalette/Palette.xcassets/Lifestyle800.colorset/Contents.json

This PR updates the Lifestyle.800 color.
Requirement:
We’ve made a slight adjustment to the lifestyle.800 colour, changing it from #FEEEF7 to #FEF1F8.
This update improves the contrast against neutral.46, ensuring it meets WCAG accessibility standards for text and background colour contrast.
- Code review from @guardian/android-developers or @guardian/ios-developers
- Optional code/API review from @guardian/client-side-infra
| Light | | |
| Dark | | |

Update Lifestyle.800 to #FEF1F8

---

.github/workflows/test.yml

This replaces the [GuardianAndroid user](https://github.com/orgs/guardian/people/GuardianAndroid) with a new [gu-android app](https://github.com/organizations/guardian/settings/apps/gu-android) in the [Test workflow](https://github.com/guardian/source-apps/actions/workflows/test.yml).
The implementation follows examples in the [create-github-app-token](https://github.com/actions/create-github-app-token) action documentation.
Tested by [check passing](https://github.com/guardian/source-apps/actions/runs/17297237622) on this PR.
Although, as with #248, there are steps that haven't been fully tested yet but permissions look correct.
See issue #246 for context.
Closes #246.
Also pinned third-party actions to commits for safety.

chore: Remove GuardianAndroid from test workflow

---

.github/dependabot.yml

This will mean dependabot looks in .github/workflows for updated GHAs, rather than under /android.
I think that in [a previous commit](https://github.com/guardian/source-apps/pull/12/files#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28) there was an overgeneralisation and GHAs were being looked for in an unexpected place.

chore: Change where dependabot looks for GHAs

---

android/build.gradle.kts
android/gradle/libs.versions.toml
android/gradle/wrapper/gradle-wrapper.properties

Upgrade Gradle, remove `kotlin-compiler-embeddable`
Checks pass.

[Chore] Upgrade Gradle to 8.14.3

---

Sources/Source/Badge/Badge.swift
Sources/Source/Components/Sub Navigation/SubNavigationItem.swift
Sources/Source/Components/Sub Navigation/SubNavigationItemColorPalette.swift
Sources/Source/Components/Sub Navigation/SubNavigationItemView.swift
Sources/Source/Components/Sub Navigation/SubNavigationView.swift

**Figma**
[Subnav Figma Link](https://www.figma.com/design/AzlT1ayOb0mv4peLWc6Ccu/My-Guardian-2.0?node-id=11801-41144&t=eX1bVJXFIfq99coI-0)
[Badge Figma Link](https://www.figma.com/design/HYKpHfksrAD4YE8P8ukN3Q/Supporter-Revenue-Toolkit?node-id=11-3&p=f&t=ydvwVygU8lmyuEVT-0)
This pull request introduces a new `Badge` component and updates the sub-navigation UI to support a "New" badge for navigation items. It also extends the colour palette for the sub nav to support badge colours and updates the relevant components to handle the new functionality.
**Other Improvements**
* Updated the preview for hidden navigation items to clarify their state in the UI. (`Sources/Source/Components/Sub Navigation/SubNavigationView.swift`)
- Code …

Add Badge component and the "New" badge for our custom sub nav
